### ISSUE TITLE
`Show model graph` does not work

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#95]
The model graph in the Expert functionalities does not work. 
It sticks like this: 

![image](https://user-images.githubusercontent.com/22169206/61543105-1dbd8080-aa43-11e9-89bf-005efce8ac34.png)

**Comment by stefanocorsi** [comment]
@ankostis the plot is not launching anymore the web server since the application has been packaged. Do you have any ideas? 

I get this message from the command line:
```
f:\dati\personale\jrc\co2mpas\.co2mpas4\lib\site-packages\schedula\utils\drw\__init__.py:799: Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == "__main__" guard to silence this warning.
  app.run(**options)
```

**Comment by ankostis** [comment]
Have no idea what triggered it.

But have you [bisected the *packaging commits*](https://git-scm.com/docs/git-bisect) and verified they did this to *co2wui*?
Because i see that *schedula* in [`schedula\utils\drw\__init__.py:799`](https://github.com/vinci1it2000/schedula/blob/master/schedula/utils/drw/__init__.py#L799) tries to launch flask again.

Maybe you could ask @vinci1it2000 to help you on that, i'm sure there should be a way to avoid launching a new flask server from within the running flask server.

**Comment by stefanocorsi** [comment]
Hi Kostis, I'll do the bisection, but I went by memory. On a local computer the funcionality was surely working before the 15th ofJuly. I'll check as well if there's a better way to launch it.

**Comment by ankostis** [comment]
Still, launching a separate web server just to view the workflow, seems plain wrong.
And that is a general comment, i.e what if calling from a jupyter notebook? Or from an ssh?
I felt the same bad test back when co2mpas was a desktop app, and decided not to bother to integrate it with the Tk GUI.

Maybe it is time to make it right, or leave it for another time.

**Comment by stefanocorsi** [comment]
You are probably right, leaving it out is an option as well as, maybe, creating a separate menu icon/link to launch it independently from the OS.

**Comment by stefanocorsi** [comment]
559e1fd
c3d2be2
